[build]
  publish = "wwwroot"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[headers]]
  for = "*.gb"
  [headers.values]
  Content-Type = "application/octet-stream"
  Cache-Control = "public, max-age=0, must-revalidate"
